apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 10
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "eduardo3g/hello-go:v6.2"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000 # container port, not the service port
            initialDelaySeconds: 10 # wait for 10sec before k8s start trying to check status
            periodSeconds: 3
            failureThreshold: 1 # if fails once, it means the app is not ready
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 8000 # container port, not the service port
          #   periodSeconds: 5
          #   failureThreshold: 3 # needs to fail 3 times to restart container
          #   timeoutSeconds: 1
          #   successThreshold: 1
              
          # env:
          #   - name: NAME
          #     valueFrom:
          #       configMapKeyRef:
          #         name: goserver-env
          #         key: NAME
          #   - name: AGE
          #     valueFrom:
          #       configMapKeyRef:
          #         name: goserver-env
          #         key: AGE
          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret
          
          # Creates a file inside the Pod (/myfamily/family.txt)
          volumeMounts:
            - mountPath: "/go/myfamily"
              name: config
              readOnly: true
      
      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
            - key: members
              path: "family.txt"