apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: ClusterIP
  ports:
  - name: goserver-service
    port: 80 # service is accessed on port 80
    targetPort: 8000 # but redirects traffic to port 8000 inside the container
    protocol: TCP